ifndef OS_VERSION
   $(error Ahven needs you to set OS_VERSION.)
endif

ahven:
	if [ -d ahven ]; then ( cd ahven && hg pull && hg update && hg revert --all ); else ( rm -f ahven && hg clone https://bitbucket.org/tkoskine/ahven ); fi
	mkdir -p tests/results

libesl:
	if [ -d libesl ]; then ( cd libesl && git pull ); else ( rm -f libesl && git clone https://github.com/AdaHeads/libesl libesl ); fi

.PHONY: ahven libesl

